### ISSUE TITLE
How to Build mediapipe_tracker.so

### ISSUE THREAD

**Issue by zhongwenkun886** [manoj7410/trackerSortAndMediaPipe#1]
hi , thanks you for your this project, it is useful for me. Could you please tell how to Build mediapipe_tracker.so. Because I want to build other modules in the mediapipe.

Thank you very much.

**Comment by manoj7410** [comment]
@zhongwenkun886 I took this lib from https://github.com/google/automl-video-ondevice. I don't have source code to  build this lib.

**Comment by zhongwenkun886** [comment]
thanks
